Description: >
    Security groups for ECS cluster template.

Parameters:

    EnvironmentName:
        Description: An environment name
        Type: String
    VPC:
        Type: AWS::EC2::VPC::Id

Resources:

    ECSHostSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            VpcId: !Ref VPC
            GroupDescription: ECS instances security group
            SecurityGroupIngress:
                - SourceSecurityGroupId: !Ref LoadBalancerSecurityGroup
                  IpProtocol: -1
            Tags:
                - Key: Name
                  Value: !Join [ "-", [ sg, $ENV_NAME, ecs, !Ref EnvironmentName] ]
                - Key: Env
                  Value: !Ref EnvironmentName

    LoadBalancerSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            VpcId: !Ref VPC
            GroupDescription: Access to the load balancer that sits in front of ECS
            SecurityGroupIngress:
                - CidrIp: 0.0.0.0/0
                  IpProtocol: -1
            Tags:
                - Key: Name
                  Value: !Join [ "-", [ sg, $ENV_NAME, lb, !Ref EnvironmentName] ]
                - Key: Env
                  Value: !Ref EnvironmentName

Outputs:

    ECSHostSecurityGroup:
        Description: A reference to the security group for ECS instances
        Value: !Ref ECSHostSecurityGroup

    LoadBalancerSecurityGroup:
        Description: A reference to the security group for load balancer
        Value: !Ref LoadBalancerSecurityGroup
