Description: >
    VPC with a pair of public subnets across two AZ template.

Parameters:

    EnvironmentName:
        Description: An environment name
        Type: String

    VpcCIDR:
        Description: VPC CIDR value
        Type: String
        Default: $VPC_CIDR

    PublicSubnet1CIDR:
        Description: CIDR for the public subnet in the first Availability Zone
        Type: String
        Default: $PublicSubnet1CIDR

    PublicSubnet2CIDR:
        Description: CIDR for the public subnet in the second Availability Zone
        Type: String
        Default: $PublicSubnet2CIDR

Resources:

    VPC:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: !Ref VpcCIDR
            Tags:
                - Key: Name
                  Value: !Join [ "-", [ vpc, $ENV_NAME, !Ref EnvironmentName] ]
                - Key: Env
                  Value: !Ref EnvironmentName

    InternetGateway:
        Type: AWS::EC2::InternetGateway
        Properties:
            Tags:
                - Key: Name
                  Value: !Join [ "-", [ igw, $ENV_NAME, !Ref EnvironmentName] ]
                - Key: Env
                  Value: !Ref EnvironmentName

    InternetGatewayAttachment:
        Type: AWS::EC2::VPCGatewayAttachment
        Properties:
            InternetGatewayId: !Ref InternetGateway
            VpcId: !Ref VPC

    PublicSubnet1:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId: !Ref VPC
            AvailabilityZone: !Select [ 0, !GetAZs ]
            CidrBlock: !Ref PublicSubnet1CIDR
            MapPublicIpOnLaunch: true
            Tags:
                - Key: Name
                  Value: !Join [ "-", [ sub, $ENV_NAME, !Ref EnvironmentName, az01] ]
                - Key: Env
                  Value: !Ref EnvironmentName

    PublicSubnet2:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId: !Ref VPC
            AvailabilityZone: !Select [ 1, !GetAZs ]
            CidrBlock: !Ref PublicSubnet2CIDR
            MapPublicIpOnLaunch: true
            Tags:
                - Key: Name
                  Value: !Join [ "-", [ sub, $ENV_NAME, !Ref EnvironmentName, az02] ]
                - Key: Env
                  Value: !Ref EnvironmentName

    PublicRouteTable:
        Type: AWS::EC2::RouteTable
        Properties:
            VpcId: !Ref VPC
            Tags:
                - Key: Name
                  Value: !Join [ "-", [ rt, $ENV_NAME, !Ref EnvironmentName] ]
                - Key: Env
                  Value: !Ref EnvironmentName

    DefaultPublicRoute:
        Type: AWS::EC2::Route
        DependsOn: InternetGatewayAttachment
        Properties:
            RouteTableId: !Ref PublicRouteTable
            DestinationCidrBlock: 0.0.0.0/0
            GatewayId: !Ref InternetGateway

    PublicSubnet1RouteTableAssociation:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            RouteTableId: !Ref PublicRouteTable
            SubnetId: !Ref PublicSubnet1

    PublicSubnet2RouteTableAssociation:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            RouteTableId: !Ref PublicRouteTable
            SubnetId: !Ref PublicSubnet2

Outputs:

    VPC:
        Description: A reference to the created VPC
        Value: !Ref VPC
        Export:
            Name: !Sub "${AWS::StackName}-VPCID"

    PublicSubnets:
        Description: A list of the subnets
        Value: !Join [ ",", [ !Ref PublicSubnet1, !Ref PublicSubnet2 ]]
